version: '2.1'
services:
  db:
    image: 'mongo:latest'
    command: mongod --port 27017
    ports:
      - '27017:27017'
    restart: always
    healthcheck:
      test: "exit 0"
      retries: 3
      timeout: 10s
      interval: 3s
    volumes:
      - .db:/data/db/

  app:
    build: docker
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
volumes:
  .db:
